# 서버 포트 번호
server:
  port: 8080

spring:
  jpa:
    # sql 표시 유무
    show-sql: true
    hibernate:
      # 데이터베이스 자동 생성 설정
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB username
    username: root
    # DB password
    password: 2936
    # DB Source URL
    url: jdbc:mysql://localhost:3306/test
    dbcp2:
      test-on-borrow: true
      validation-query: select 1
